export enum JustifyContent {
  Center = "center",
  End = "end",
  FlexEnd = "flex-end",
  FlexStart = "flex-start",
  Inherit = "inherit",
  Initial = "initial",
  Left = "left",
  Normal = "normal",
  Right = "right",
  SpaceAround = "space-around",
  SpaceBetween = "space-between",
  SpaceEvenly = "space-evenly",
  Start = "start",
  Stretch = "stretch",
  Unset = "unset",
}
